import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"
import Footer from "./_components/footer"
import AuthProvider from "./_providers/auth"
import WhatsAppButton from "./_components/whatsapp-button"
import { db } from "./_lib/prisma"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const settings = await db.settings.findFirst()

  return (
    <html lang="pt-br" className="dark bg-[#1D1D1D]">
      <body className={inter.className}>
        <AuthProvider>
          <div className="flex h-full flex-col">
            <div className="flex-1">{children}</div>
            <Footer />
          </div>
          <WhatsAppButton phoneNumber={settings?.phones[0] || ""} />
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  )
}
